// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHzkb7j3dnr9wjNCFI1J1Au9jOytm2MW8',
    appId: '1:722736931109:web:36de581a40f093e336bacc',
    messagingSenderId: '722736931109',
    projectId: 'event-management-a9cc1',
    authDomain: 'event-management-a9cc1.firebaseapp.com',
    storageBucket: 'event-management-a9cc1.appspot.com',
    measurementId: 'G-4J5XSH1WH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmhRPMl8-gN9iTVVdnYJuH3A3NhU_hPNU',
    appId: '1:722736931109:android:9a0b5591824f83bd36bacc',
    messagingSenderId: '722736931109',
    projectId: 'event-management-a9cc1',
    storageBucket: 'event-management-a9cc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVE8bn6hfDRFYHpOd0B1PagTzBQHkS5s8',
    appId: '1:722736931109:ios:354e943d581d143d36bacc',
    messagingSenderId: '722736931109',
    projectId: 'event-management-a9cc1',
    storageBucket: 'event-management-a9cc1.appspot.com',
    iosClientId: '722736931109-igkgc1s4odn8gjk8nlqpff5gg87tvjj3.apps.googleusercontent.com',
    iosBundleId: 'com.example.schedulerApp',
  );
}
